# Generated by Django 3.2 on 2021-04-20 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['-title'], 'verbose_name': 'Chapters on project'},
        ),
        migrations.AlterModelOptions(
            name='progress_type',
            options={'ordering': ['-type_of_progress'], 'verbose_name': 'Progress by card'},
        ),
    ]
